name: Baidu Netdisk Sign-in

on:
  schedule:
    - cron: '0 23 * * *'

  workflow_dispatch:

jobs:
  sign-in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Baidu Sign-in
        env:
          BAIDU_COOKIE: ${{ secrets.BAIDU_COOKIE }}
        run: |
          python baidu_signin.py
